In [ ]:
num = float(input("Enter a number: "))
if num >= 0:
   if num == 0:
       print("Zero")
   else:
       print("Positive number")
else:
   print("Negative number")

Enter a number: 0
Zero


In [ ]:
sub1=int(input("Enter marks of the first subject: "))
sub2=int(input("Enter marks of the second subject: "))
sub3=int(input("Enter marks of the third subject: "))
sub4=int(input("Enter marks of the fourth subject: "))
sub5=int(input("Enter marks of the fifth subject: "))
avg=(sub1+sub2+sub3+sub4+sub5)/5
if(avg>=90):
    print("Grade: A")
elif(avg >= 80 & avg < 90):
    print("Grade: B")
elif(avg >= 70 & avg < 80):
    print("Grade: C")
elif(avg >= 60 & avg < 70):
    print("Grade: D")
else:
    print("Grade: F")

Enter marks of the first subject: 97
Enter marks of the second subject: 95
Enter marks of the third subject: 91
Enter marks of the fourth subject: 89
Enter marks of the fifth subject: 96
Grade: A


In [ ]:
x=10
while x>5:
  print(x),
x-=1

In [ ]:
x=1
while x<10:
  print (x);
x+=1

Streaming output truncated to the last 5000 lines.
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1

KeyboardInterrupt: ignored

In [ ]:
n = int(input("Enter the number of rows"))  
# outer loop to handle number of rows  
for i in range(0, n):  
    # inner loop to handle number of columns  
    # values is changing according to outer loop  
        for j in range(0, i + 1):  
            # printing stars  
            print("* ", end="")       
  
        # ending line after each row  
        print() 

Enter the number of rows4
* 
* * 
* * * 
* * * * 


In [ ]:
rows = int(input("Enter the number of rows: "))  
  
# It is used to print the space  
k = 2 * rows - 2  
# Outer loop to print number of rows  
for i in range(0, rows):  
    # Inner loop is used to print number of space  
    for j in range(0, k):  
        print(end=" ")  
    # Decrement in k after each iteration  
    k = k - 1  
    # This inner loop is used to print stars  
    for j in range(0, i + 1):  
        print("* ", end="")  
    print("")  
  
# Downward triangle Pyramid  
# It is used to print the space  
k = rows - 2  
# Output for downward triangle pyramid  
for i in range(rows, -1, -1):  
    # inner loop will print the spaces  
    for j in range(k, 0, -1):  
        print(end=" ")  
    # Increment in k after each iteration  
    k = k + 1  
    # This inner loop will print number of stars  
    for j in range(0, i + 1):  
        print("* ", end="")  
    print("")  

Enter the number of rows: 2
  * 
 * * 
* * * 
 * * 
  * 


In [ ]:
p = input("first value : ")
q = input("second value : ")
j = 0
k = int(input("rows you want? : "))
while k >= 1:
    print(" "*j + (k-1)*(p+q) +p+ " "*j)
    k = k-1
    j=j+1

first value : 1
second value : 0
rows you want? : 4
1010101
 10101 
  101  
   1   


In [ ]:
max = 100
num = 1

while num <= max:
    if(num % 2 == 0):
        print("{0}".format(num))
    num = num + 1

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [ ]:
number = int(input("Please Enter any Number: "))
total = 0

for value in range(1, number + 1):
    total = total + value

print("The Sum of Natural Numbers from 1 to {0} =  {1}".format(number, total))


Please Enter any Number: 10
The Sum of Natural Numbers from 1 to 10 =  55


dictionary = {'MSBTE' : 'Maharashtra State Board of Technical Education',
'CO' : 'Computer Engineering',
'SEM' : 'Sixth'}
del dictionary['CO'];
for key, values in dictionary.items(): 
  print(key)
  dictionary.clear();
for key, values in dictionary.items():
  print(key)
  del dictionary;
for key, values in dictionary.items():
  print(key)

In [ ]:
dictionary = {'MSBTE' : 'Maharashtra State Board of Technical Education',
'CO' : 'Computer Engineering',
'SEM' : 'Sixth'
}
del dictionary['CO'];
for key, values in dictionary.items():
  print(key)
dictionary.clear();
for key, values in dictionary.items():
  print(key)
del dictionary;
for key, values in dictionary.items():
  print(key)

MSBTE
SEM


NameError: ignored

In [ ]:
dictionary1 = {'Google' : 1,
'Facebook' : 2,
'Microsoft' : 3
}
dictionary2 = {'GFG' : 1,
'Microsoft' : 2,
'Youtube' : 3
}
dictionary1.update(dictionary2);
for key, values in dictionary1.items():
  print(key, values)

Google 1
Facebook 2
Microsoft 2
GFG 1
Youtube 3


In [ ]:
temp = dict()
temp['key1'] = {'key1' : 44, 'key2' : 566}
temp['key2'] = [1, 2, 3, 4]
for (key, values) in temp.items():
  print(values, end = "")

{'key1': 44, 'key2': 566}[1, 2, 3, 4]

In [ ]:
import operator

d = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}

s= sorted(d.items(), key=operator.itemgetter(1))

print('ascending order : ',s)

s1= dict( sorted(d.items(), key=operator.itemgetter(1),reverse=True))

print('descending order : ',s1)

ascending order :  [(0, 0), (2, 1), (1, 2), (4, 3), (3, 4)]
descending order :  {3: 4, 4: 3, 1: 2, 2: 1, 0: 0}


In [ ]:
# Python program to demonstrate
# finding 3 highest values in a Dictionary

from collections import Counter

# Initial Dictionary
my_dict = {'A': 67, 'B': 23, 'C': 45,
        'D': 56, 'E': 12, 'F': 69}

k = Counter(my_dict)

# Finding 3 highest values
high = k.most_common(3)

print("Initial Dictionary:")
print(my_dict, "\n")


print("Dictionary with 3 highest values:")
print("Keys: Values")

for i in high:
    print(i[0]," :",i[1]," ")

Initial Dictionary:
{'A': 67, 'B': 23, 'C': 45, 'D': 56, 'E': 12, 'F': 69} 

Dictionary with 3 highest values:
Keys: Values
F  : 69  
A  : 67  
D  : 56  


In [ ]:
# Python Title() Method Example

str1 = 'geeKs foR geEks'
str2 = str1.title()
print('First Output after Title() method is = ', str2)


First Output after Title() method is =  Geeks For Geeks


In [ ]:
# Python program to demonstrate the
# use of capitalize() function

# capitalize() first letter of
# string.
name = "geeks for geeks"

print(name.capitalize())

Geeks for geeks


In [ ]:
def string_test(s):
    d={"UPPER_CASE":0, "LOWER_CASE":0}
    for c in s:
        if c.isupper():
           d["UPPER_CASE"]+=1
        elif c.islower():
           d["LOWER_CASE"]+=1
        else:
           pass
    print ("Original String : ", s)
    print ("No. of Upper case characters : ", d["UPPER_CASE"])
    print ("No. of Lower case Characters : ", d["LOWER_CASE"])

string_test('The quick Brown Fox')


Original String :  The quick Brown Fox
No. of Upper case characters :  3
No. of Lower case Characters :  13


In [ ]:
import random

print(random.uniform(5,50))


37.057085979180734


In [ ]:
def myfunc(text, num):
  while num > 0:
    print(text)
    num = num - 1
myfunc('Hello', 4)

Hello
Hello
Hello
Hello


In [ ]:
num = 1
def func():
  num = 3
  print(num)
func()
print(num)

3
1


In [ ]:
def test_prime(n):
    if (n==1):
        return False
    elif (n==2):
        return True;
    else:
        for x in range(2,n):
            if(n % x==0):
                return False
        return True             
print(test_prime(6))


False


Input a number to compute the factiorial : 4
24


In [ ]:
import math
math.sqrt(25)
math.pi
math.degrees (2)
math.radians(60)
math.sin(2)
math.cos(0.5)
math.tan(0.23)
math.factorial(4)

24

In [ ]:
import random
random.randint(0, 5)
random.random()
random.random() * 100
List = [1, 4, True, 800, "Python", 27, "hello"]
random.choice(List)

4

In [ ]:
import datetime
from datetime import date
import time
time.time()
date.fromtimestamp(454554)

datetime.date(1970, 1, 6)

In [ ]:
def greeting(name):
  name=input("College Name: ")

In [ ]:
import math

# Reading temperature in Celsius
radius = float(input('Enter radius of circle: '))
 
# Calculating area and circumference
area = math.pi * radius ** 2
circumference = 2 * math.pi * radius

# Displaying output
print('Area = %0.4f.' % (area))
print('Circumference = %0.4f.' % (circumference))

Enter radius of circle: 4
Area = 50.2655.
Circumference = 25.1327.


In [ ]:
import calendar  
# Enter the month and year  
yy = int(input("Enter year: "))  
mm = int(input("Enter month: "))  
  
# display the calendar  
print(calendar.month(yy,mm))  

Enter year: 2022
Enter month: 7
     July 2022
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



In [ ]:
import numpy
# Two matrices are initialized by value
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])
#  add()is used to add matrices
print ("Addition of two matrices: ")
print (numpy.add(x,y))
# subtract()is used to subtract matrices
print ("Subtraction of two matrices : ")
print (numpy.subtract(x,y))
# divide()is used to divide matrices
print ("Matrix Division : ")
print (numpy.divide(x,y))
print ("Multiplication of two matrices: ")
print (numpy.multiply(x,y))

Addition of two matrices: 
[[ 8 10]
 [13 15]]
Subtraction of two matrices : 
[[-6 -6]
 [-5 -5]]
Matrix Division : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
Multiplication of two matrices: 
[[ 7 16]
 [36 50]]


In [ ]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[11 12 17 11 20 17]


In [ ]:
class Animal:
# properties
  multicellular = True
# Eukaryotic means Cells with Nucleus
eukaryotic = True
# function breath
def breathe(self):
  print("I breathe oxygen.")
# function feed
def feed(self):
  print("I eat food.")
# child class
class Herbivorous(Animal):
# function feed
 def feed(self):
  print("I eat only plants. I am vegetarian.")
herbi = Herbivorous()
herbi.feed()
# calling some other function
herbi.breathe()

I eat only plants. I am vegetarian.


AttributeError: ignored